/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Recommendation;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-05-12T13:45:36.790+08:00")

@Api(value = "default", description = "the default API")
public interface DefaultApi {

    @ApiOperation(value = "Get recommendations", nickname = "rootGet", notes = "Get recommendations", response = Recommendation.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "test", response = Recommendation.class) })
    @RequestMapping(value = "/",
        produces = { "application/json" }, 
        consumes = { "*/*" },
        method = RequestMethod.GET)
    ResponseEntity<Recommendation> rootGet();


    @ApiOperation(value = "tet", nickname = "rootPost", notes = "Create Recommendation", response = Recommendation.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "test", response = Recommendation.class) })
    @RequestMapping(value = "/",
        method = RequestMethod.POST)
    ResponseEntity<Recommendation> rootPost(@ApiParam(value = ""  )  @Valid @RequestBody Recommendation body);

}
